Feat : Complete Daily Challenge
delta/codecharacter-server-2023 pull request #15
Opened 2023-02-09 17:57 UTC by shubham-1806

2023-02-14 16:48 UTC, Ram-20062003 requested changes
- [x] Have `map validator` check for `CODE AS QUESTION` challenges
- [x] Have better meaningful names for the variable 
- [ ] Revert back the deleted `SchedulingService` file.
- [ ] Add `BattleTV` support also for `DCs`.
- [ ] Look into grammatical errors also:sneezing_face:

2023-02-14 16:48 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/logic/daily_challenge_score/DailyChallengeScoreAlgorithm.kt
> +            .toInt() / 100.0
Is this toInt() needed ?

2023-02-14 16:48 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/daily_challenge/DailyChallengeService.kt
>      @Value("\${environment.event-start-date}") val tempDate: String = ""
```suggestion
    @Value("\${environment.event-start-date}") private lateinit var currentDate: String
```

2023-02-14 16:48 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/logic/daily_challenge_score/DailyChallengeScoreAlgorithm.kt
> +    @Value("\${environment.event-start-date}") val tempDate: String = ""
```suggestion
    @Value("\${environment.event-start-date}") private lateinit var tempDate: String
```

2023-02-14 16:48 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/logic/daily_challenge_score/DailyChallengeScoreAlgorithm.kt
> +        val totalCoins = gameConfiguration.gameParameters().numberOfCoins
You don't have to create an `instance` and call again. `GameParameter` is already a `bean` just autowire and inject it

2023-02-14 16:48 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/user/public_user/PublicUserEntity.kt
> +    val dailyChallengeHistory: HashMap<UUID, DailyChallengeHistory>
It should be a `HashMap` of  Day number and a `Dataclass` of *Score*,*DailychallengeEntity*

2023-02-14 16:48 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/daily_challenge/DailyChallengeService.kt
> +        val dc = dailyChallengeRepository.findByDay(findNumberOfDays()).get()
Instead you can make use of the `getDailyChallengeByDate()` function already declared in `DailyChallengeService.kt` .

2023-02-14 16:48 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/user/public_user/DailyChallengeHistory.kt
> +data class DailyChallengeHistory(val score: Double, val day: Int)
```suggestion
data class DailyChallengeHistory(val score: Double, val challenge: DailyChallengeEntity)
```

2023-02-14 16:48 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/match/MatchService.kt
> +                        DailyChallengeMatchVerdictEnum.SUCCESS -> "Successfully Completed Challenge"
```suggestion
                        DailyChallengeMatchVerdictEnum.SUCCESS -> "Successfully completed challenge"
```

2023-02-14 16:48 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/match/MatchService.kt
> +                        }
```suggestion
                        else -> {
                            "Failed to complete challenge"
                        }
```

2023-02-14 16:48 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/match/MatchService.kt
> +                HttpStatus.BAD_REQUEST, "You have already completed your daily Challenge"
```suggestion
                HttpStatus.BAD_REQUEST, "You have already completed your daily challenge"
```

2023-02-24 13:25 UTC, Ram-20062003 requested changes

2023-02-24 13:25 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/match/MatchService.kt
> +                throw IllegalStateException("MatchMode Is Not Correct")
```suggestion
                throw CustomExeption(HttpStatus.BAD_REQUEST,"MatchMode Is Not Correct")
```

2023-02-24 13:25 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/daily_challenge/DailyChallengeController.kt
> +        return ResponseEntity.ok(dailyChallengeService.getDailyChallengeByDateForUser(userId))
```suggestion
        return ResponseEntity.ok(dailyChallengeService.getDailyChallengeByDateForUser(user.id))
```

2023-02-24 13:25 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/daily_challenge/DailyChallengeService.kt
>                  throw CustomException(org.springframework.http.HttpStatus.BAD_REQUEST, "Invalid Request")
```suggestion
        return dailyChallengeRepository.findByDay(findNumberOfDays()).orElseThrow {
                throw CustomException(HttpStatus.BAD_REQUEST, "Invalid day for daily challenge")
            }
```

2023-02-24 13:25 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/daily_challenge/DailyChallengeService.kt
> +        val dc = getDailyChallengeByDate()
`dc` -> `currentDailyChallenge` everywhere

2023-02-24 13:25 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/daily_challenge/DailyChallengeService.kt
> +            val updatedDc = dc.copy(numberOfCompletions = dc.numberOfCompletions + 1)
`updatedDc` -> `updatedDailyChallenge` everywhere

2023-02-24 13:25 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/logic/daily_challenge_score/DailyChallengeScoreAlgorithm.kt
> +        val totalCoins = gameConfiguration.gameParameters().numberOfCoins
Please use `gameParameter` bean here

2023-02-24 13:25 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/logic/daily_challenge_score/DailyChallengeScoreAlgorithm.kt
> +        val perfectTimePart = 0.3 * perfectScore
Declare all constants (0.7,0.3,150 ) in separate variables and use variables here.Give proper naming for all constants too.
For example,
- private val perfectBaseScoreConstant = 0.7
- private val perfectTimeScoreConstant = 0.3

2023-02-24 13:25 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/logic/daily_challenge_score/DailyChallengeScoreAlgorithm.kt
> +    override fun getTimeScore(perfectTimeScore: Double): Double {
`getTimeScore` -> `getPlayerTimeScore`

2023-02-24 13:25 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/logic/daily_challenge_score/DailyChallengeScoreAlgorithm.kt
> +        return perfectTimeScore * exp((-1) * (hours / 15))
Declare constant (15) in variable and use that variable here as said earlier.

2023-02-24 13:25 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/logic/daily_challenge_score/ScoreAlgorithm.kt
> +    fun getTimeScore(
`getTimeScore` -> `getPlayerTimeScore`

2023-02-24 13:25 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/match/MatchService.kt
> +                    }
Add `DailyChallengeMatchVerdictEnum.FAILURE` separately and in `else` mention `Some error occured. Try again!`.

2023-02-24 13:25 UTC, Ram-20062003 commented
Please, add the changes done in this PR in description.

2023-02-26 18:35 UTC, Ram-20062003 approved these changes

2023-02-26 18:36 UTC, vigneshd332 approved these changes

2023-02-26 18:37 UTC, merged