feat: Updated README.md, defaultCodeModularity, added submodules
delta/codecharacter-server-2023 pull request #16
Opened 2023-02-09 20:06 UTC by ZaBarudo

2023-02-09 21:35 UTC, Ram-20062003 requested changes

2023-02-09 21:35 UTC, Ram-20062003 commented on .gitmodules
> +[submodule "codeMapConfig"]
```suggestion
[submodule "player_code"]
```

2023-02-09 21:35 UTC, Ram-20062003 commented on .gitmodules
> +	path = server/src/main/resources/codeMapConfig
```suggestion
	path = server/src/main/resources/player_code
```

2023-02-09 21:35 UTC, Ram-20062003 commented on README.md
> +6. Run `git submodule update --init` or `git submodule add --name codeMapConfig https://github.com/delta/codecharacter-default-codes-2022 server/src/main/resources/codeMapConfig`
```suggestion
6. Run `git submodule update --init` 
```

2023-02-09 21:35 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/config/DefaultCodeMapConfiguration.kt
> +        {}::class.java.classLoader.getResource("codeMapConfig/cpp/run.cpp")?.readText() ?: "",
```suggestion
        DefaultCodeMapConfiguration::class.java.classLoader.getResource("codeMapConfig/cpp/run.cpp")?.readText() ?: "",
```

2023-02-10 20:03 UTC, Ram-20062003 commented
While updating .gitmodules, please clear the previous .git/modules and in .git/config

2023-02-10 20:05 UTC, Ram-20062003 requested changes

2023-02-10 20:05 UTC, Ram-20062003 commented on .gitmodules
> +[submodule "player_code"]
- While updating .gitmodules, please clear the previous .git/modules and in .git/config

2023-02-11 16:23 UTC, Ram-20062003 approved these changes

2023-02-14 17:44 UTC, Ashwin125 approved these changes

2023-02-14 22:15 UTC, merged