update(Update game entities): Updated Attackers and Defenders
delta/codecharacter-server-2023 pull request #17
Opened 2023-02-10 08:59 UTC by b1otch

### Updated Attackers and Defenders

- Updated the attacker and defender values
- Added aerial attribute

2023-02-10 19:48 UTC, Ram-20062003 commented
why did u delete pre-commit.sh?.

2023-02-14 22:52 UTC, Ram-20062003 requested changes
## Changes Requested
- Fix the parameter namings and change it wherever it is being used

2023-02-14 22:52 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/params/game_entities/Attacker.kt
> +    @field:JsonProperty("is_aerial", required = true) val type: Boolean,
```suggestion
    @field:JsonProperty("is_aerial", required = true) val attackerType: Boolean,
```

2023-02-14 22:52 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/params/game_entities/Defender.kt
> +    @field:JsonProperty("is_aerial", required = true) val type: Boolean,
```suggestion
    @field:JsonProperty("is_aerial", required = true) val defenderType: Boolean,
```

2023-02-18 18:42 UTC, Ram-20062003 approved these changes

2023-02-18 18:44 UTC, Ashwin125 approved these changes

2023-02-18 18:46 UTC, merged