Add tutorial completion check
delta/codecharacter-server-2023 pull request #7
Opened 2023-01-01 06:45 UTC by Valliammai-SM

2023-01-14 21:23 UTC, Ram-20062003 requested changes
## Changes Requested
- [ ] Pull rebase your PR
- [ ] Change `user.recaptchaKey` -> `environment.recaptchaKey` (yaml format)
- [ ] Make your corresponding changes in `application.docker.example.yml` also
- [ ] `UpdateTutorial` is not proper. Fix it
- [ ] Fix recaptcha verification

2023-01-14 21:23 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/user/UserService.kt
> +
why `updatetutorial` is a separate function in the `userservice`. Tutorial update is present with this common [/user(patch)](https://delta.github.io/codecharacter-server-2023/spec/index.html#/current-user/updateCurrentUser)  route. Update it over there

2023-01-14 21:23 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/user/UserService.kt
> +            val request=HttpRequest.newBuilder().uri(URI.create(url)).POST(HttpRequest.BodyPublishers.ofString(requestBody)).build()
```suggestion
            val request=HttpRequest.newBuilder().uri(URI.create(recaptchaUrl)).POST(HttpRequest.BodyPublishers.noBody()).build()
```
- `Request-body` should not be passed

2023-01-14 21:23 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/user/UserService.kt
> +            val requestBody = ObjectMapper().writeValueAsString(mapOf("secret" to secretKey,"response" to reCaptchaResponse))
```suggestion
            val recaptchaUrl =             "https://www.google.com/recaptcha/api/siteverify?secret=${secretKey}&response=${reCaptchaResponse}"
```
- The `recaptcha-url` will be accepting the `secret` and `recaptchaCode` as `params` not as `request body`. [Check Here](https://developers.google.com/recaptcha/docs/verify)

2023-01-14 21:23 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/user/UserService.kt
> +            "https://www.google.com/recaptcha/api/siteverify"
```suggestion
 
```

2023-01-14 21:23 UTC, Ram-20062003 commented on server/src/main/resources/application.example.yml
> +  reCaptcha-key: your-reCaptcha-key
put this under `environment` itself ,

2023-01-21 14:19 UTC, Ram-20062003 approved these changes

2023-01-21 14:22 UTC, Ashwin125 approved these changes

2023-01-21 17:48 UTC, Ashwin125 approved these changes

2023-01-22 12:31 UTC, vigneshd332 approved these changes

2023-01-22 12:31 UTC, Ram-20062003 approved these changes

2023-01-22 12:32 UTC, merged