feat(Daily Challenge LeaderBoard): Added the DailyChallengeLeaderboard
delta/codecharacter-server-2023 pull request #8
Opened 2023-01-02 17:43 UTC by b1otch

## In this PR
- Added Daily Challenge Leaderboard

2023-01-03 10:05 UTC, Ram-20062003 requested changes

2023-01-03 10:05 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/daily_challenges/DailyChallengeEntity.kt
> +)
This file is not used anywhere for fetching leaderboard details. You can remove this

2023-01-03 10:05 UTC, Ram-20062003 commented on server/src/main/kotlin/delta/codecharacter/server/daily_challenges/DailyChallengesRepository.kt
> +interface DailyChallengesRepository : MongoRepository<DailyChallengeEntity, UUID>
This file is not used.You can remove this file

2023-01-05 17:21 UTC, Ram-20062003 approved these changes

2023-01-06 08:15 UTC, vigneshd332 approved these changes

2023-01-06 08:17 UTC, merged